image.tag: 0.1.0.84dfc14-RC

extraEnv:
  - name : MAESTRO_KAFKA_BROKER
    value: "kafka:9092"

  - name : MAESTRO_KAFKA_INDEXING_TOPIC
    value: "maestro_index_requests"

  - name : MAESTRO_SONG_MAX_RETRIES
    value: "3"

  - name : MAESTRO_SONG_TIMEOUT_SEC_STUDY
    value: "100"

  - name : MAESTRO_SONG_TIMEOUT_SEC_ANALYSIS
    value: "5"

  - name : MAESTRO_SONG_INDEXABLE_STUDY_STATUS
    value: "PUBLISHED"

  - name : MAESTRO_EXCLUSION_RULES_FILE_NAME
    value: "exclusion-rules.yml"

  - name : MAESTRO_ELASTICSEARCH_CLUSTER_NODES
    value: "elasticsearch-master:9200"

  - name : MAESTRO_ELASTICSEARCH_INDEXES_FILE_CENTRIC_ALIAS
    value: "file_centric"

  - name : MAESTRO_ELASTICSEARCH_CLIENT_DOCS_PER_BULK_REQ_MAX
    value: "5000"

  - name : MAESTRO_ELASTICSEARCH_CLIENT_CONNECTION_TIMEOUT
    value: "5000"

  - name : MAESTRO_ELASTICSEARCH_CLIENT_SOCKET_TIMEOUT
    value: "10000"

  - name : MAESTRO_ELASTICSEARCH_CLIENT_RETRY_MAX_ATTEMPTS
    value: "3"

  - name : MAESTRO_ELASTICSEARCH_CLIENT_RETRY_WAIT_DURATION_MILLIS
    value: "500"

  - name : MAESTRO_REPOSITORIES_0_CODE
    value: "collab"

  - name : MAESTRO_REPOSITORIES_0_URL
    value: "https://song.cancercollaboratory.org"

  - name : MAESTRO_REPOSITORIES_0_NAME
    value: "collaboratory"

  - name : MAESTRO_REPOSITORIES_0_DATAPATH
    value: "/oicr.icgc/data"

  - name : MAESTRO_REPOSITORIES_0_METADATAPATH
    value: "/oicr.icgc.meta/metadata"

  - name : MAESTRO_REPOSITORIES_0_STORAGETYPE
    value: "S3"

  - name : MAESTRO_REPOSITORIES_0_ORGANIZATION
    value: "ICGC"

  - name : MAESTRO_REPOSITORIES_0_COUNTRY
    value: "CA"

  - name : MAESTRO_REPOSITORIES_1_CODE
    value: "aws"

  - name : MAESTRO_REPOSITORIES_1_URL
    value: "https://virginia.song.icgc.org"

  - name : MAESTRO_REPOSITORIES_1_NAME
    value: "aws virginia"

  - name : MAESTRO_REPOSITORIES_1_METADATAPATH
    value: "/oicr.icgc.meta/metadata"

  - name : MAESTRO_REPOSITORIES_1_STORAGETYPE
    value: "S3"

  - name : MAESTRO_REPOSITORIES_1_ORGANIZATION
    value: "ICGC"

  - name : MAESTRO_REPOSITORIES_1_COUNTRY
    value: "US"

  - name : MAESTRO_FAILURE_LOG_ENABLED
    value: "true"

  - name : MAESTRO_FAILURE_LOG_DIR
    value: "/app-logs"

  - name : LOGGING_LEVEL_ROOT
    value: "INFO"

  - name : LOGGING_LEVEL_BIO_OVERTURE
    value: "TRACE"

  - name : LOGGING_LEVEL_BIO_OVERTURE_MAESTRO_DOMAIN_ENTITIES_INDEXING_RULES_IDEXCLUSIONRULE
    value: "INFO"

  - name : LOGGING_LEVEL_ORG_APACHE_KAFKA_CLIENTS
    value: "WARN"

  - name : MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    value: "*"

  - name : MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
    value: "ALWAYS"

  - name : SPRING_APPLICATION_NAME
    value: "maestro"

  - name : SPRING_OUTPUT_ANSI_ENABLED
    value: "ALWAYS"

  - name : SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
    value: "${maestro.kafka.broker}"

  - name : SPRING_CLOUD_STREAM_BINDINGS_INPUT_DESTINATION
    value: "${maestro.kafka.indexing_topic}"