image.tag: edge
image:
  pullPolicy: Always

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: maestro.qa.overture.bio
      paths:
        - /

extraEnv:
  MAESTRO_ELASTICSEARCH_CLUSTERNODES_0: "http://elasticsearch-master:9200"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "kafka-overture-qa-cp-kafka:9092"
  # repos
  MAESTRO_REPOSITORIES_0_CODE: "collab"
  MAESTRO_REPOSITORIES_0_URL: "https://song.cancercollaboratory.org"
  MAESTRO_REPOSITORIES_0_NAME: "collaboratory"
  MAESTRO_REPOSITORIES_0_ORGANIZATION: "ICGC"
  MAESTRO_REPOSITORIES_0_COUNTRY: "CA"
  MAESTRO_REPOSITORIES_1_CODE: "song.overture"
  MAESTRO_REPOSITORIES_1_URL: "http://song-qa:8080"
  MAESTRO_REPOSITORIES_1_NAME: "local song"
  MAESTRO_REPOSITORIES_1_ORGANIZATION: "overture"
  MAESTRO_REPOSITORIES_1_COUNTRY: "OICR"
  # slack
  MAESTRO_NOTIFICATIONS_SLACK_ENABLED: "true"
  MAESTRO_NOTIFICATIONS_SLACK_URL: "secret"
  MAESTRO_NOTIFICATIONS_SLACK_CHANNEL: "maestro-argo-notif"


